# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:

- repo: https://github.com/pycqa/flake8
  rev: 7.1.1
  hooks:
    - id: flake8
      args: ["--count", "--max-line-length=80", "--statistics", "--exclude", "plugins"]
      files: ^gsrest/.*\.py$

- repo: local
  hooks:
    - id: code-format
      name: Code Format (AutoPEP8 + YAPF)
      entry: |
        bash -c 'autopep8 --in-place --recursive gsrest && yapf --in-place --recursive gsrest'
      language: system
      pass_filenames: false
      always_run: true
      files: ^gsrest/.*\.py$


    - id: generate-openapi-server
      name: Generate OpenAPI Server
      entry: make generate-openapi-server
      language: system
      pass_filenames: false
      always_run: true

    - id: update-openapi-version
      name: Update OpenAPI Version
      entry: make update-openapi-version
      pass_filenames: false
      language: system
      always_run: true