openapi: 3.0.0
info:
  description: GraphSense API
  title: GraphSense API
  version: 0.4.4
servers:
- url: http://openapi_server:9000
paths:
  /{currency}/blocks:
    get:
      operationId: list_blocks
      parameters:
      - description: The currency
        example: btc
        explode: false
        in: path
        name: currency
        required: true
        schema:
          format: string
          type: string
        style: simple
      - description: Resumption token for retrieving the next page
        example: 0400030bff00f07fffff9b00
        explode: true
        in: query
        name: page
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/blocks'
          description: OK
      summary: Get all blocks
      tags:
      - blocks
      x-openapi-router-controller: openapi_server.controllers.blocks_controller
  /{currency}/blocks/{height}:
    get:
      operationId: get_block
      parameters:
      - description: The currency
        example: btc
        explode: false
        in: path
        name: currency
        required: true
        schema:
          format: string
          type: string
        style: simple
      - description: The block height
        example: 1
        explode: false
        in: path
        name: height
        required: true
        schema:
          minimum: 1
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/block'
          description: OK
      summary: Get a block by its height
      tags:
      - blocks
      x-openapi-router-controller: openapi_server.controllers.blocks_controller
  /{currency}/blocks/{height}/txs:
    get:
      operationId: list_block_txs
      parameters:
      - description: The currency
        example: btc
        explode: false
        in: path
        name: currency
        required: true
        schema:
          format: string
          type: string
        style: simple
      - description: The block height
        example: 1
        explode: false
        in: path
        name: height
        required: true
        schema:
          minimum: 1
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/block_txs'
          description: OK
      summary: Get all blocks (100 per page)
      tags:
      - blocks
      x-openapi-router-controller: openapi_server.controllers.blocks_controller
  /{currency}/blocks/{height}/txs.csv:
    get:
      operationId: list_block_txs_csv
      parameters:
      - description: The currency
        example: btc
        explode: false
        in: path
        name: currency
        required: true
        schema:
          format: string
          type: string
        style: simple
      - description: The block height
        example: 1
        explode: false
        in: path
        name: height
        required: true
        schema:
          minimum: 1
          type: integer
        style: simple
      responses:
        "200":
          content:
            text/csv:
              schema:
                items:
                  $ref: '#/components/schemas/block_tx_summary'
                type: array
          description: OK
      summary: Get all blocks as CSV
      tags:
      - blocks
      x-openapi-router-controller: openapi_server.controllers.blocks_controller
  /{currency}/stats:
    get:
      operationId: get_statistics
      parameters:
      - description: The currency
        example: btc
        explode: false
        in: path
        name: currency
        required: true
        schema:
          format: string
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/currency'
          description: OK
      summary: Get statistics of currency
      tags:
      - general
      x-openapi-router-controller: openapi_server.controllers.general_controller
components:
  parameters:
    currency:
      description: The currency
      example: btc
      explode: false
      in: path
      name: currency
      required: true
      schema:
        format: string
        type: string
      style: simple
    height:
      description: The block height
      example: 1
      explode: false
      in: path
      name: height
      required: true
      schema:
        minimum: 1
        type: integer
      style: simple
    page:
      description: Resumption token for retrieving the next page
      example: 0400030bff00f07fffff9b00
      explode: true
      in: query
      name: page
      required: false
      schema:
        type: string
      style: form
  schemas:
    stats:
      properties:
        currencies:
          $ref: '#/components/schemas/stats_currencies'
      type: object
    currency:
      example:
        no_addresses: 1
        no_labels: 2
        no_entities: 5
        no_address_relations: 6
        no_blocks: 0
        no_txs: 5
        timestamp: 7
      properties:
        no_blocks:
          format: int64
          type: integer
        no_address_relations:
          format: int64
          type: integer
        no_addresses:
          format: int64
          type: integer
        no_entities:
          format: int64
          type: integer
        no_txs:
          format: int64
          type: integer
        no_labels:
          format: int64
          type: integer
        timestamp:
          format: int64
          type: integer
      title: a cryptocurrency
      type: object
    block:
      example:
        block_hash: block_hash
        height: 0
        no_txs: 6
        timestamp: 1
      properties:
        block_hash:
          format: string
          type: string
        height:
          format: int64
          type: integer
        no_txs:
          format: int64
          type: integer
        timestamp:
          format: int64
          type: integer
      type: object
    block_txs:
      example:
        txs:
        - total_output:
            eur: 5
            usd: 5
            value: 2
          no_outputs: 1
          total_input:
            eur: 5
            usd: 5
            value: 2
          tx_hash: tx_hash
          no_inputs: 6
        - total_output:
            eur: 5
            usd: 5
            value: 2
          no_outputs: 1
          total_input:
            eur: 5
            usd: 5
            value: 2
          tx_hash: tx_hash
          no_inputs: 6
        height: 0
      properties:
        height:
          type: integer
        txs:
          items:
            $ref: '#/components/schemas/block_tx_summary'
          type: array
      type: object
    block_tx_summary:
      example:
        total_output:
          eur: 5
          usd: 5
          value: 2
        no_outputs: 1
        total_input:
          eur: 5
          usd: 5
          value: 2
        tx_hash: tx_hash
        no_inputs: 6
      properties:
        tx_hash:
          type: string
        no_inputs:
          format: int64
          type: integer
        no_outputs:
          format: int64
          type: integer
        total_input:
          $ref: '#/components/schemas/converted_values'
        total_output:
          $ref: '#/components/schemas/converted_values'
      type: object
    blocks:
      example:
        next_page: next_page
        blocks:
        - block_hash: block_hash
          height: 0
          no_txs: 6
          timestamp: 1
        - block_hash: block_hash
          height: 0
          no_txs: 6
          timestamp: 1
      properties:
        next_page:
          format: string
          type: string
        blocks:
          items:
            $ref: '#/components/schemas/block'
          type: array
      type: object
    converted_values:
      example:
        eur: 5
        usd: 5
        value: 2
      properties:
        eur:
          format: int64
          type: integer
        usd:
          format: int64
          type: integer
        value:
          format: int64
          type: integer
      type: object
    next_page:
      format: string
      type: string
    stats_currencies:
      properties:
        btc:
          $ref: '#/components/schemas/currency'
        bch:
          $ref: '#/components/schemas/currency'
        ltc:
          $ref: '#/components/schemas/currency'
        zec:
          $ref: '#/components/schemas/currency'
