# coding: utf-8

"""
    GraphSense API

    GraphSense API provides programmatic access to various ledgers' addresses, entities, blocks, transactions and tags for automated and highly efficient forensics tasks.  # noqa: E501

    Contact: contact@ikna.io
    Generated by: https://openapi-generator.tech
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import field_validator,  BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from graphsense.compat import CompatInt
from typing import Any, ClassVar, Dict, List, Optional
from graphsense.models.values import Values
from typing import Optional, Set
from typing_extensions import Self

class AddressTxUtxo(BaseModel):
    """
    UTXO transaction for an address.
    """ # noqa: E501
    tx_type: Optional[StrictStr] = 'utxo'
    tx_hash: StrictStr
    currency: StrictStr
    coinbase: StrictBool
    height: int
    timestamp: StrictInt
    value: Values
    __properties: ClassVar[List[str]] = ["tx_type", "tx_hash", "currency", "coinbase", "height", "timestamp", "value"]
    @field_validator('height', mode='wrap')
    @classmethod
    def wrap_height_compat(cls, v, handler):
        """Wrap height in CompatInt for backward compatibility."""
        validated = handler(v)
        if validated is not None and not isinstance(validated, CompatInt):
            return CompatInt(validated)
        return validated


    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AddressTxUtxo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of value
        if self.value:
            _dict['value'] = self.value.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AddressTxUtxo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "tx_type": obj.get("tx_type") if obj.get("tx_type") is not None else 'utxo',
            "tx_hash": obj.get("tx_hash"),
            "currency": obj.get("currency"),
            "coinbase": obj.get("coinbase"),
            "height": obj.get("height"),
            "timestamp": obj.get("timestamp"),
            "value": Values.from_dict(obj["value"]) if obj.get("value") is not None else None
        })
        return _obj


