# coding: utf-8

"""
    GraphSense API

    GraphSense API provides programmatic access to various ledgers' addresses, entities, blocks, transactions and tags for automated and highly efficient forensics tasks.  # noqa: E501

    Contact: contact@ikna.io
    Generated by: https://openapi-generator.tech
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from graphsense.models.address import Address
from graphsense.models.values import Values
from typing import Optional, Set
from typing_extensions import Self

class NeighborAddress(BaseModel):
    """
    Neighbor address model.
    """ # noqa: E501
    value: Values
    no_txs: StrictInt
    address: Address
    labels: Optional[List[StrictStr]] = None
    token_values: Optional[Dict[str, Values]] = None
    __properties: ClassVar[List[str]] = ["value", "no_txs", "address", "labels", "token_values"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NeighborAddress from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of value
        if self.value:
            _dict['value'] = self.value.to_dict()
        # override the default output from pydantic by calling `to_dict()` of address
        if self.address:
            _dict['address'] = self.address.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each value in token_values (dict)
        _field_dict = {}
        if self.token_values:
            for _key_token_values in self.token_values:
                if self.token_values[_key_token_values]:
                    _field_dict[_key_token_values] = self.token_values[_key_token_values].to_dict()
            _dict['token_values'] = _field_dict

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NeighborAddress from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "value": Values.from_dict(obj["value"]) if obj.get("value") is not None else None,
            "no_txs": obj.get("no_txs"),
            "address": Address.from_dict(obj["address"]) if obj.get("address") is not None else None,
            "labels": obj.get("labels"),
            "token_values": dict(
                (_k, Values.from_dict(_v))
                for _k, _v in obj["token_values"].items()
            )
            if obj.get("token_values") is not None
            else None
        })
        return _obj


