# coding: utf-8

"""
    GraphSense API

    GraphSense API provides programmatic access to various ledgers' addresses, entities, blocks, transactions and tags for automated and highly efficient forensics tasks.  # noqa: E501

    Contact: contact@ikna.io
    Generated by: https://openapi-generator.tech
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from graphsense.models.label_summary import LabelSummary
from graphsense.models.tag_cloud_entry import TagCloudEntry
from typing import Optional, Set
from typing_extensions import Self

class TagSummary(BaseModel):
    """
    Tag summary model.
    """ # noqa: E501
    broad_category: StrictStr
    tag_count: StrictInt
    label_summary: Dict[str, LabelSummary]
    concept_tag_cloud: Dict[str, TagCloudEntry]
    tag_count_indirect: Optional[StrictInt] = None
    best_actor: Optional[StrictStr] = None
    best_label: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["broad_category", "tag_count", "label_summary", "concept_tag_cloud", "tag_count_indirect", "best_actor", "best_label"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TagSummary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in label_summary (dict)
        _field_dict = {}
        if self.label_summary:
            for _key_label_summary in self.label_summary:
                if self.label_summary[_key_label_summary]:
                    _field_dict[_key_label_summary] = self.label_summary[_key_label_summary].to_dict()
            _dict['label_summary'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each value in concept_tag_cloud (dict)
        _field_dict = {}
        if self.concept_tag_cloud:
            for _key_concept_tag_cloud in self.concept_tag_cloud:
                if self.concept_tag_cloud[_key_concept_tag_cloud]:
                    _field_dict[_key_concept_tag_cloud] = self.concept_tag_cloud[_key_concept_tag_cloud].to_dict()
            _dict['concept_tag_cloud'] = _field_dict

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TagSummary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "broad_category": obj.get("broad_category"),
            "tag_count": obj.get("tag_count"),
            "label_summary": dict(
                (_k, LabelSummary.from_dict(_v))
                for _k, _v in obj["label_summary"].items()
            )
            if obj.get("label_summary") is not None
            else None,
            "concept_tag_cloud": dict(
                (_k, TagCloudEntry.from_dict(_v))
                for _k, _v in obj["concept_tag_cloud"].items()
            )
            if obj.get("concept_tag_cloud") is not None
            else None,
            "tag_count_indirect": obj.get("tag_count_indirect"),
            "best_actor": obj.get("best_actor"),
            "best_label": obj.get("best_label")
        })
        return _obj


