# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model_ import Model
from openapi_server.models.address_tag import AddressTag
from openapi_server import util


class AddressTags(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, address_tags: List[AddressTag]=None, next_page: str=None):
        """AddressTags - a model defined in OpenAPI

        :param address_tags: The address_tags of this AddressTags.
        :param next_page: The next_page of this AddressTags.
        """
        self.openapi_types = {
            'address_tags': List[AddressTag],
            'next_page': str
        }

        self.attribute_map = {
            'address_tags': 'address_tags',
            'next_page': 'next_page'
        }

        self._address_tags = address_tags
        self._next_page = next_page

    @classmethod
    def from_dict(cls, dikt: dict) -> 'AddressTags':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The address_tags of this AddressTags.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def address_tags(self):
        """Gets the address_tags of this AddressTags.


        :return: The address_tags of this AddressTags.
        :rtype: List[AddressTag]
        """
        return self._address_tags

    @address_tags.setter
    def address_tags(self, address_tags):
        """Sets the address_tags of this AddressTags.


        :param address_tags: The address_tags of this AddressTags.
        :type address_tags: List[AddressTag]
        """
        if address_tags is None:
            raise ValueError("Invalid value for `address_tags`, must not be `None`")

        self._address_tags = address_tags

    @property
    def next_page(self):
        """Gets the next_page of this AddressTags.


        :return: The next_page of this AddressTags.
        :rtype: str
        """
        return self._next_page

    @next_page.setter
    def next_page(self, next_page):
        """Sets the next_page of this AddressTags.


        :param next_page: The next_page of this AddressTags.
        :type next_page: str
        """

        self._next_page = next_page
