# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.tag import Tag
from openapi_server import util

from openapi_server.models.tag import Tag  # noqa: E501

class AddressWithTagsAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, tags=None):  # noqa: E501
        """AddressWithTagsAllOf - a model defined in OpenAPI

        :param tags: The tags of this AddressWithTagsAllOf.  # noqa: E501
        :type tags: List[Tag]
        """
        self.openapi_types = {
            'tags': List[Tag]
        }

        self.attribute_map = {
            'tags': 'tags'
        }

        self._tags = tags

    @classmethod
    def from_dict(cls, dikt) -> 'AddressWithTagsAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The address_with_tags_allOf of this AddressWithTagsAllOf.  # noqa: E501
        :rtype: AddressWithTagsAllOf
        """
        return util.deserialize_model(dikt, cls)

    def to_dict(self, prefix=""):
        """Returns the model as a dict:

        :return: The AddressWithTagsAllOf as a dict
        :rtype: dict
        """
        return { 'tags': self._tags }


    @property
    def tags(self):
        """Gets the tags of this AddressWithTagsAllOf.

        Tags  # noqa: E501

        :return: The tags of this AddressWithTagsAllOf.
        :rtype: List[Tag]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this AddressWithTagsAllOf.

        Tags  # noqa: E501

        :param tags: The tags of this AddressWithTagsAllOf.
        :type tags: List[Tag]
        """

        self._tags = tags
