# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.address import Address
from openapi_server import util

from openapi_server.models.address import Address  # noqa: E501

class Addresses(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, addresses=None, next_page=None):  # noqa: E501
        """Addresses - a model defined in OpenAPI

        :param addresses: The addresses of this Addresses.  # noqa: E501
        :type addresses: List[Address]
        :param next_page: The next_page of this Addresses.  # noqa: E501
        :type next_page: str
        """
        self.openapi_types = {
            'addresses': List[Address],
            'next_page': str
        }

        self.attribute_map = {
            'addresses': 'addresses',
            'next_page': 'next_page'
        }

        self._addresses = addresses
        self._next_page = next_page

    @classmethod
    def from_dict(cls, dikt) -> 'Addresses':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The addresses of this Addresses.  # noqa: E501
        :rtype: Addresses
        """
        return util.deserialize_model(dikt, cls)

    def to_dict(self, prefix=""):
        """Returns the model as a dict:

        :return: The Addresses as a dict
        :rtype: dict
        """
        return { 'addresses': self._addresses,
            'next_page': self._next_page }


    @property
    def addresses(self):
        """Gets the addresses of this Addresses.


        :return: The addresses of this Addresses.
        :rtype: List[Address]
        """
        return self._addresses

    @addresses.setter
    def addresses(self, addresses):
        """Sets the addresses of this Addresses.


        :param addresses: The addresses of this Addresses.
        :type addresses: List[Address]
        """

        self._addresses = addresses

    @property
    def next_page(self):
        """Gets the next_page of this Addresses.


        :return: The next_page of this Addresses.
        :rtype: str
        """
        return self._next_page

    @next_page.setter
    def next_page(self, next_page):
        """Sets the next_page of this Addresses.


        :param next_page: The next_page of this Addresses.
        :type next_page: str
        """

        self._next_page = next_page
