# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model_ import Model
from openapi_server.models.address_tx_utxo import AddressTxUtxo
from openapi_server.models.tx_account import TxAccount
from openapi_server.models.values import Values
from openapi_server import util


class AddressTx(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, tx_type: str='account', tx_hash: str=None, height: int=None, timestamp: int=None, value: Values=None, from_address: str=None, to_address: str=None):
        """AddressTx - a model defined in OpenAPI

        :param tx_type: The tx_type of this AddressTx.
        :param tx_hash: The tx_hash of this AddressTx.
        :param height: The height of this AddressTx.
        :param timestamp: The timestamp of this AddressTx.
        :param value: The value of this AddressTx.
        :param from_address: The from_address of this AddressTx.
        :param to_address: The to_address of this AddressTx.
        """
        self.openapi_types = {
            'tx_type': str,
            'tx_hash': str,
            'height': int,
            'timestamp': int,
            'value': Values,
            'from_address': str,
            'to_address': str
        }

        self.attribute_map = {
            'tx_type': 'tx_type',
            'tx_hash': 'tx_hash',
            'height': 'height',
            'timestamp': 'timestamp',
            'value': 'value',
            'from_address': 'from_address',
            'to_address': 'to_address'
        }

        self._tx_type = tx_type
        self._tx_hash = tx_hash
        self._height = height
        self._timestamp = timestamp
        self._value = value
        self._from_address = from_address
        self._to_address = to_address

    @classmethod
    def from_dict(cls, dikt: dict) -> 'AddressTx':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The address_tx of this AddressTx.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def tx_type(self):
        """Gets the tx_type of this AddressTx.


        :return: The tx_type of this AddressTx.
        :rtype: str
        """
        return self._tx_type

    @tx_type.setter
    def tx_type(self, tx_type):
        """Sets the tx_type of this AddressTx.


        :param tx_type: The tx_type of this AddressTx.
        :type tx_type: str
        """
        if tx_type is None:
            raise ValueError("Invalid value for `tx_type`, must not be `None`")

        self._tx_type = tx_type

    @property
    def tx_hash(self):
        """Gets the tx_hash of this AddressTx.

        Transaction hash

        :return: The tx_hash of this AddressTx.
        :rtype: str
        """
        return self._tx_hash

    @tx_hash.setter
    def tx_hash(self, tx_hash):
        """Sets the tx_hash of this AddressTx.

        Transaction hash

        :param tx_hash: The tx_hash of this AddressTx.
        :type tx_hash: str
        """
        if tx_hash is None:
            raise ValueError("Invalid value for `tx_hash`, must not be `None`")

        self._tx_hash = tx_hash

    @property
    def height(self):
        """Gets the height of this AddressTx.

        Height

        :return: The height of this AddressTx.
        :rtype: int
        """
        return self._height

    @height.setter
    def height(self, height):
        """Sets the height of this AddressTx.

        Height

        :param height: The height of this AddressTx.
        :type height: int
        """
        if height is None:
            raise ValueError("Invalid value for `height`, must not be `None`")
        if height is not None and height < 0:
            raise ValueError("Invalid value for `height`, must be a value greater than or equal to `0`")

        self._height = height

    @property
    def timestamp(self):
        """Gets the timestamp of this AddressTx.

        Timestamp

        :return: The timestamp of this AddressTx.
        :rtype: int
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this AddressTx.

        Timestamp

        :param timestamp: The timestamp of this AddressTx.
        :type timestamp: int
        """
        if timestamp is None:
            raise ValueError("Invalid value for `timestamp`, must not be `None`")

        self._timestamp = timestamp

    @property
    def value(self):
        """Gets the value of this AddressTx.


        :return: The value of this AddressTx.
        :rtype: Values
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this AddressTx.


        :param value: The value of this AddressTx.
        :type value: Values
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")

        self._value = value

    @property
    def from_address(self):
        """Gets the from_address of this AddressTx.

        Address

        :return: The from_address of this AddressTx.
        :rtype: str
        """
        return self._from_address

    @from_address.setter
    def from_address(self, from_address):
        """Sets the from_address of this AddressTx.

        Address

        :param from_address: The from_address of this AddressTx.
        :type from_address: str
        """
        if from_address is None:
            raise ValueError("Invalid value for `from_address`, must not be `None`")

        self._from_address = from_address

    @property
    def to_address(self):
        """Gets the to_address of this AddressTx.

        Address

        :return: The to_address of this AddressTx.
        :rtype: str
        """
        return self._to_address

    @to_address.setter
    def to_address(self, to_address):
        """Sets the to_address of this AddressTx.

        Address

        :param to_address: The to_address of this AddressTx.
        :type to_address: str
        """
        if to_address is None:
            raise ValueError("Invalid value for `to_address`, must not be `None`")

        self._to_address = to_address
