# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class AddressTagAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, address=None):  # noqa: E501
        """AddressTagAllOf - a model defined in OpenAPI

        :param address: The address of this AddressTagAllOf.  # noqa: E501
        :type address: str
        """
        self.openapi_types = {
            'address': str
        }

        self.attribute_map = {
            'address': 'address'
        }

        if address is None:
            raise ValueError("Invalid value for `address`, must not be `None`")  # noqa: E501
        self._address = address

    @classmethod
    def from_dict(cls, dikt) -> 'AddressTagAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The address_tag_allOf of this AddressTagAllOf.  # noqa: E501
        :rtype: AddressTagAllOf
        """
        return util.deserialize_model(dikt, cls)

    def to_dict(self, prefix=""):
        """Returns the model as a dict:

        :return: The AddressTagAllOf as a dict
        :rtype: dict
        """
        return { 'address': self._address }


    @property
    def address(self):
        """Gets the address of this AddressTagAllOf.

        Address  # noqa: E501

        :return: The address of this AddressTagAllOf.
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this AddressTagAllOf.

        Address  # noqa: E501

        :param address: The address of this AddressTagAllOf.
        :type address: str
        """
        if address is None:
            raise ValueError("Invalid value for `address`, must not be `None`")  # noqa: E501

        self._address = address
