# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Concept(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, description=None, id=None, label=None, taxonomy=None, uri=None):  # noqa: E501
        """Concept - a model defined in OpenAPI

        :param description: The description of this Concept.  # noqa: E501
        :type description: str
        :param id: The id of this Concept.  # noqa: E501
        :type id: str
        :param label: The label of this Concept.  # noqa: E501
        :type label: str
        :param taxonomy: The taxonomy of this Concept.  # noqa: E501
        :type taxonomy: str
        :param uri: The uri of this Concept.  # noqa: E501
        :type uri: str
        """
        self.openapi_types = {
            'description': str,
            'id': str,
            'label': str,
            'taxonomy': str,
            'uri': str
        }

        self.attribute_map = {
            'description': 'description',
            'id': 'id',
            'label': 'label',
            'taxonomy': 'taxonomy',
            'uri': 'uri'
        }

        #if description is None:
            #raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501
        self._description = description
        #if id is None:
            #raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501
        self._id = id
        #if label is None:
            #raise ValueError("Invalid value for `label`, must not be `None`")  # noqa: E501
        self._label = label
        #if taxonomy is None:
            #raise ValueError("Invalid value for `taxonomy`, must not be `None`")  # noqa: E501
        self._taxonomy = taxonomy
        #if uri is None:
            #raise ValueError("Invalid value for `uri`, must not be `None`")  # noqa: E501
        self._uri = uri

    @classmethod
    def from_dict(cls, dikt) -> 'Concept':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The concept of this Concept.  # noqa: E501
        :rtype: Concept
        """
        return util.deserialize_model(dikt, cls)

    def to_dict(self, prefix=""):
        """Returns the model as a dict:

        :return: The Concept as a dict
        :rtype: dict
        """
        return { 'description': self._description,
            'id': self._id,
            'label': self._label,
            'taxonomy': self._taxonomy,
            'uri': self._uri }


    @property
    def description(self):
        """Gets the description of this Concept.

        Description  # noqa: E501

        :return: The description of this Concept.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Concept.

        Description  # noqa: E501

        :param description: The description of this Concept.
        :type description: str
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description

    @property
    def id(self):
        """Gets the id of this Concept.

        ID  # noqa: E501

        :return: The id of this Concept.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Concept.

        ID  # noqa: E501

        :param id: The id of this Concept.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def label(self):
        """Gets the label of this Concept.

        Label  # noqa: E501

        :return: The label of this Concept.
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this Concept.

        Label  # noqa: E501

        :param label: The label of this Concept.
        :type label: str
        """
        if label is None:
            raise ValueError("Invalid value for `label`, must not be `None`")  # noqa: E501

        self._label = label

    @property
    def taxonomy(self):
        """Gets the taxonomy of this Concept.

        Taxonomy  # noqa: E501

        :return: The taxonomy of this Concept.
        :rtype: str
        """
        return self._taxonomy

    @taxonomy.setter
    def taxonomy(self, taxonomy):
        """Sets the taxonomy of this Concept.

        Taxonomy  # noqa: E501

        :param taxonomy: The taxonomy of this Concept.
        :type taxonomy: str
        """
        if taxonomy is None:
            raise ValueError("Invalid value for `taxonomy`, must not be `None`")  # noqa: E501

        self._taxonomy = taxonomy

    @property
    def uri(self):
        """Gets the uri of this Concept.

        URI  # noqa: E501

        :return: The uri of this Concept.
        :rtype: str
        """
        return self._uri

    @uri.setter
    def uri(self, uri):
        """Sets the uri of this Concept.

        URI  # noqa: E501

        :param uri: The uri of this Concept.
        :type uri: str
        """
        if uri is None:
            raise ValueError("Invalid value for `uri`, must not be `None`")  # noqa: E501

        self._uri = uri
