# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.entity import Entity
from openapi_server.models.entity_with_tags_all_of import EntityWithTagsAllOf
from openapi_server.models.tag import Tag
from openapi_server.models.tx_summary import TxSummary
from openapi_server.models.values import Values
from openapi_server import util

from openapi_server.models.entity import Entity  # noqa: E501
from openapi_server.models.entity_with_tags_all_of import EntityWithTagsAllOf  # noqa: E501
from openapi_server.models.tag import Tag  # noqa: E501
from openapi_server.models.tx_summary import TxSummary  # noqa: E501
from openapi_server.models.values import Values  # noqa: E501

class EntityWithTags(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, entity=None, balance=None, first_tx=None, last_tx=None, in_degree=None, out_degree=None, no_addresses=None, no_incoming_txs=None, no_outgoing_txs=None, total_received=None, total_spent=None, tags=None, tag_coherence=None):  # noqa: E501
        """EntityWithTags - a model defined in OpenAPI

        :param entity: The entity of this EntityWithTags.  # noqa: E501
        :type entity: str
        :param balance: The balance of this EntityWithTags.  # noqa: E501
        :type balance: Values
        :param first_tx: The first_tx of this EntityWithTags.  # noqa: E501
        :type first_tx: TxSummary
        :param last_tx: The last_tx of this EntityWithTags.  # noqa: E501
        :type last_tx: TxSummary
        :param in_degree: The in_degree of this EntityWithTags.  # noqa: E501
        :type in_degree: int
        :param out_degree: The out_degree of this EntityWithTags.  # noqa: E501
        :type out_degree: int
        :param no_addresses: The no_addresses of this EntityWithTags.  # noqa: E501
        :type no_addresses: int
        :param no_incoming_txs: The no_incoming_txs of this EntityWithTags.  # noqa: E501
        :type no_incoming_txs: int
        :param no_outgoing_txs: The no_outgoing_txs of this EntityWithTags.  # noqa: E501
        :type no_outgoing_txs: int
        :param total_received: The total_received of this EntityWithTags.  # noqa: E501
        :type total_received: Values
        :param total_spent: The total_spent of this EntityWithTags.  # noqa: E501
        :type total_spent: Values
        :param tags: The tags of this EntityWithTags.  # noqa: E501
        :type tags: List[Tag]
        :param tag_coherence: The tag_coherence of this EntityWithTags.  # noqa: E501
        :type tag_coherence: float
        """
        self.openapi_types = {
            'entity': str,
            'balance': Values,
            'first_tx': TxSummary,
            'last_tx': TxSummary,
            'in_degree': int,
            'out_degree': int,
            'no_addresses': int,
            'no_incoming_txs': int,
            'no_outgoing_txs': int,
            'total_received': Values,
            'total_spent': Values,
            'tags': List[Tag],
            'tag_coherence': float
        }

        self.attribute_map = {
            'entity': 'entity',
            'balance': 'balance',
            'first_tx': 'first_tx',
            'last_tx': 'last_tx',
            'in_degree': 'in_degree',
            'out_degree': 'out_degree',
            'no_addresses': 'no_addresses',
            'no_incoming_txs': 'no_incoming_txs',
            'no_outgoing_txs': 'no_outgoing_txs',
            'total_received': 'total_received',
            'total_spent': 'total_spent',
            'tags': 'tags',
            'tag_coherence': 'tag_coherence'
        }

        if entity is None:
            raise ValueError("Invalid value for `entity`, must not be `None`")  # noqa: E501
        self._entity = entity
        if balance is None:
            raise ValueError("Invalid value for `balance`, must not be `None`")  # noqa: E501
        self._balance = balance
        if first_tx is None:
            raise ValueError("Invalid value for `first_tx`, must not be `None`")  # noqa: E501
        self._first_tx = first_tx
        if last_tx is None:
            raise ValueError("Invalid value for `last_tx`, must not be `None`")  # noqa: E501
        self._last_tx = last_tx
        if in_degree is None:
            raise ValueError("Invalid value for `in_degree`, must not be `None`")  # noqa: E501
        self._in_degree = in_degree
        if out_degree is None:
            raise ValueError("Invalid value for `out_degree`, must not be `None`")  # noqa: E501
        self._out_degree = out_degree
        if no_addresses is None:
            raise ValueError("Invalid value for `no_addresses`, must not be `None`")  # noqa: E501
        self._no_addresses = no_addresses
        if no_incoming_txs is None:
            raise ValueError("Invalid value for `no_incoming_txs`, must not be `None`")  # noqa: E501
        self._no_incoming_txs = no_incoming_txs
        if no_outgoing_txs is None:
            raise ValueError("Invalid value for `no_outgoing_txs`, must not be `None`")  # noqa: E501
        self._no_outgoing_txs = no_outgoing_txs
        if total_received is None:
            raise ValueError("Invalid value for `total_received`, must not be `None`")  # noqa: E501
        self._total_received = total_received
        if total_spent is None:
            raise ValueError("Invalid value for `total_spent`, must not be `None`")  # noqa: E501
        self._total_spent = total_spent
        if tags is None:
            raise ValueError("Invalid value for `tags`, must not be `None`")  # noqa: E501
        self._tags = tags
        self._tag_coherence = tag_coherence

    @classmethod
    def from_dict(cls, dikt) -> 'EntityWithTags':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The entity_with_tags of this EntityWithTags.  # noqa: E501
        :rtype: EntityWithTags
        """
        return util.deserialize_model(dikt, cls)

    def to_dict(self, prefix=""):
        """Returns the model as a dict:

        :return: The EntityWithTags as a dict
        :rtype: dict
        """
        return { 'entity': self._entity,
            'balance': self._balance,
            'first_tx': self._first_tx,
            'last_tx': self._last_tx,
            'in_degree': self._in_degree,
            'out_degree': self._out_degree,
            'no_addresses': self._no_addresses,
            'no_incoming_txs': self._no_incoming_txs,
            'no_outgoing_txs': self._no_outgoing_txs,
            'total_received': self._total_received,
            'total_spent': self._total_spent,
            'tags': self._tags,
            'tag_coherence': self._tag_coherence }


    @property
    def entity(self):
        """Gets the entity of this EntityWithTags.

        Entity id  # noqa: E501

        :return: The entity of this EntityWithTags.
        :rtype: str
        """
        return self._entity

    @entity.setter
    def entity(self, entity):
        """Sets the entity of this EntityWithTags.

        Entity id  # noqa: E501

        :param entity: The entity of this EntityWithTags.
        :type entity: str
        """
        if entity is None:
            raise ValueError("Invalid value for `entity`, must not be `None`")  # noqa: E501

        self._entity = entity

    @property
    def balance(self):
        """Gets the balance of this EntityWithTags.


        :return: The balance of this EntityWithTags.
        :rtype: Values
        """
        return self._balance

    @balance.setter
    def balance(self, balance):
        """Sets the balance of this EntityWithTags.


        :param balance: The balance of this EntityWithTags.
        :type balance: Values
        """
        if balance is None:
            raise ValueError("Invalid value for `balance`, must not be `None`")  # noqa: E501

        self._balance = balance

    @property
    def first_tx(self):
        """Gets the first_tx of this EntityWithTags.


        :return: The first_tx of this EntityWithTags.
        :rtype: TxSummary
        """
        return self._first_tx

    @first_tx.setter
    def first_tx(self, first_tx):
        """Sets the first_tx of this EntityWithTags.


        :param first_tx: The first_tx of this EntityWithTags.
        :type first_tx: TxSummary
        """
        if first_tx is None:
            raise ValueError("Invalid value for `first_tx`, must not be `None`")  # noqa: E501

        self._first_tx = first_tx

    @property
    def last_tx(self):
        """Gets the last_tx of this EntityWithTags.


        :return: The last_tx of this EntityWithTags.
        :rtype: TxSummary
        """
        return self._last_tx

    @last_tx.setter
    def last_tx(self, last_tx):
        """Sets the last_tx of this EntityWithTags.


        :param last_tx: The last_tx of this EntityWithTags.
        :type last_tx: TxSummary
        """
        if last_tx is None:
            raise ValueError("Invalid value for `last_tx`, must not be `None`")  # noqa: E501

        self._last_tx = last_tx

    @property
    def in_degree(self):
        """Gets the in_degree of this EntityWithTags.


        :return: The in_degree of this EntityWithTags.
        :rtype: int
        """
        return self._in_degree

    @in_degree.setter
    def in_degree(self, in_degree):
        """Sets the in_degree of this EntityWithTags.


        :param in_degree: The in_degree of this EntityWithTags.
        :type in_degree: int
        """
        if in_degree is None:
            raise ValueError("Invalid value for `in_degree`, must not be `None`")  # noqa: E501

        self._in_degree = in_degree

    @property
    def out_degree(self):
        """Gets the out_degree of this EntityWithTags.


        :return: The out_degree of this EntityWithTags.
        :rtype: int
        """
        return self._out_degree

    @out_degree.setter
    def out_degree(self, out_degree):
        """Sets the out_degree of this EntityWithTags.


        :param out_degree: The out_degree of this EntityWithTags.
        :type out_degree: int
        """
        if out_degree is None:
            raise ValueError("Invalid value for `out_degree`, must not be `None`")  # noqa: E501

        self._out_degree = out_degree

    @property
    def no_addresses(self):
        """Gets the no_addresses of this EntityWithTags.


        :return: The no_addresses of this EntityWithTags.
        :rtype: int
        """
        return self._no_addresses

    @no_addresses.setter
    def no_addresses(self, no_addresses):
        """Sets the no_addresses of this EntityWithTags.


        :param no_addresses: The no_addresses of this EntityWithTags.
        :type no_addresses: int
        """
        if no_addresses is None:
            raise ValueError("Invalid value for `no_addresses`, must not be `None`")  # noqa: E501

        self._no_addresses = no_addresses

    @property
    def no_incoming_txs(self):
        """Gets the no_incoming_txs of this EntityWithTags.


        :return: The no_incoming_txs of this EntityWithTags.
        :rtype: int
        """
        return self._no_incoming_txs

    @no_incoming_txs.setter
    def no_incoming_txs(self, no_incoming_txs):
        """Sets the no_incoming_txs of this EntityWithTags.


        :param no_incoming_txs: The no_incoming_txs of this EntityWithTags.
        :type no_incoming_txs: int
        """
        if no_incoming_txs is None:
            raise ValueError("Invalid value for `no_incoming_txs`, must not be `None`")  # noqa: E501

        self._no_incoming_txs = no_incoming_txs

    @property
    def no_outgoing_txs(self):
        """Gets the no_outgoing_txs of this EntityWithTags.


        :return: The no_outgoing_txs of this EntityWithTags.
        :rtype: int
        """
        return self._no_outgoing_txs

    @no_outgoing_txs.setter
    def no_outgoing_txs(self, no_outgoing_txs):
        """Sets the no_outgoing_txs of this EntityWithTags.


        :param no_outgoing_txs: The no_outgoing_txs of this EntityWithTags.
        :type no_outgoing_txs: int
        """
        if no_outgoing_txs is None:
            raise ValueError("Invalid value for `no_outgoing_txs`, must not be `None`")  # noqa: E501

        self._no_outgoing_txs = no_outgoing_txs

    @property
    def total_received(self):
        """Gets the total_received of this EntityWithTags.


        :return: The total_received of this EntityWithTags.
        :rtype: Values
        """
        return self._total_received

    @total_received.setter
    def total_received(self, total_received):
        """Sets the total_received of this EntityWithTags.


        :param total_received: The total_received of this EntityWithTags.
        :type total_received: Values
        """
        if total_received is None:
            raise ValueError("Invalid value for `total_received`, must not be `None`")  # noqa: E501

        self._total_received = total_received

    @property
    def total_spent(self):
        """Gets the total_spent of this EntityWithTags.


        :return: The total_spent of this EntityWithTags.
        :rtype: Values
        """
        return self._total_spent

    @total_spent.setter
    def total_spent(self, total_spent):
        """Sets the total_spent of this EntityWithTags.


        :param total_spent: The total_spent of this EntityWithTags.
        :type total_spent: Values
        """
        if total_spent is None:
            raise ValueError("Invalid value for `total_spent`, must not be `None`")  # noqa: E501

        self._total_spent = total_spent

    @property
    def tags(self):
        """Gets the tags of this EntityWithTags.

        Tags  # noqa: E501

        :return: The tags of this EntityWithTags.
        :rtype: List[Tag]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this EntityWithTags.

        Tags  # noqa: E501

        :param tags: The tags of this EntityWithTags.
        :type tags: List[Tag]
        """
        if tags is None:
            raise ValueError("Invalid value for `tags`, must not be `None`")  # noqa: E501

        self._tags = tags

    @property
    def tag_coherence(self):
        """Gets the tag_coherence of this EntityWithTags.

        Tag coherence  # noqa: E501

        :return: The tag_coherence of this EntityWithTags.
        :rtype: float
        """
        return self._tag_coherence

    @tag_coherence.setter
    def tag_coherence(self, tag_coherence):
        """Sets the tag_coherence of this EntityWithTags.

        Tag coherence  # noqa: E501

        :param tag_coherence: The tag_coherence of this EntityWithTags.
        :type tag_coherence: float
        """

        self._tag_coherence = tag_coherence
