# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model_ import Model
from openapi_server.models.address import Address
from openapi_server import util


class EntityAddresses(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, addresses: List[Address]=None, next_page: str=None):
        """EntityAddresses - a model defined in OpenAPI

        :param addresses: The addresses of this EntityAddresses.
        :param next_page: The next_page of this EntityAddresses.
        """
        self.openapi_types = {
            'addresses': List[Address],
            'next_page': str
        }

        self.attribute_map = {
            'addresses': 'addresses',
            'next_page': 'next_page'
        }

        self._addresses = addresses
        self._next_page = next_page

    @classmethod
    def from_dict(cls, dikt: dict) -> 'EntityAddresses':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The entity_addresses of this EntityAddresses.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def addresses(self):
        """Gets the addresses of this EntityAddresses.


        :return: The addresses of this EntityAddresses.
        :rtype: List[Address]
        """
        return self._addresses

    @addresses.setter
    def addresses(self, addresses):
        """Sets the addresses of this EntityAddresses.


        :param addresses: The addresses of this EntityAddresses.
        :type addresses: List[Address]
        """

        self._addresses = addresses

    @property
    def next_page(self):
        """Gets the next_page of this EntityAddresses.


        :return: The next_page of this EntityAddresses.
        :rtype: str
        """
        return self._next_page

    @next_page.setter
    def next_page(self, next_page):
        """Sets the next_page of this EntityAddresses.


        :param next_page: The next_page of this EntityAddresses.
        :type next_page: str
        """

        self._next_page = next_page
