# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model_ import Model
from openapi_server.models.entity import Entity
from openapi_server import util


class Entities(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, next_page: str=None, entities: List[Entity]=None):
        """Entities - a model defined in OpenAPI

        :param next_page: The next_page of this Entities.
        :param entities: The entities of this Entities.
        """
        self.openapi_types = {
            'next_page': str,
            'entities': List[Entity]
        }

        self.attribute_map = {
            'next_page': 'next_page',
            'entities': 'entities'
        }

        self._next_page = next_page
        self._entities = entities

    @classmethod
    def from_dict(cls, dikt: dict) -> 'Entities':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The entities of this Entities.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def next_page(self):
        """Gets the next_page of this Entities.


        :return: The next_page of this Entities.
        :rtype: str
        """
        return self._next_page

    @next_page.setter
    def next_page(self, next_page):
        """Sets the next_page of this Entities.


        :param next_page: The next_page of this Entities.
        :type next_page: str
        """

        self._next_page = next_page

    @property
    def entities(self):
        """Gets the entities of this Entities.


        :return: The entities of this Entities.
        :rtype: List[Entity]
        """
        return self._entities

    @entities.setter
    def entities(self, entities):
        """Sets the entities of this Entities.


        :param entities: The entities of this Entities.
        :type entities: List[Entity]
        """

        self._entities = entities
