# coding: utf-8
from gsrest.errors import BadUserInputException
from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model_ import Model
from openapi_server import util


class ExternalConversions(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, conversion_type: str=None, from_address: str=None, to_address: str=None, from_asset: str=None, to_asset: str=None, from_amount: str=None, to_amount: str=None, from_payment: str=None, to_payment: str=None, from_network: str=None, to_network: str=None):
        """ExternalConversions - a model defined in OpenAPI

        :param conversion_type: The conversion_type of this ExternalConversions.
        :param from_address: The from_address of this ExternalConversions.
        :param to_address: The to_address of this ExternalConversions.
        :param from_asset: The from_asset of this ExternalConversions.
        :param to_asset: The to_asset of this ExternalConversions.
        :param from_amount: The from_amount of this ExternalConversions.
        :param to_amount: The to_amount of this ExternalConversions.
        :param from_payment: The from_payment of this ExternalConversions.
        :param to_payment: The to_payment of this ExternalConversions.
        :param from_network: The from_network of this ExternalConversions.
        :param to_network: The to_network of this ExternalConversions.
        """
        self.openapi_types = {
            'conversion_type': str,
            'from_address': str,
            'to_address': str,
            'from_asset': str,
            'to_asset': str,
            'from_amount': str,
            'to_amount': str,
            'from_payment': str,
            'to_payment': str,
            'from_network': str,
            'to_network': str
        }

        self.attribute_map = {
            'conversion_type': 'conversion_type',
            'from_address': 'from_address',
            'to_address': 'to_address',
            'from_asset': 'from_asset',
            'to_asset': 'to_asset',
            'from_amount': 'from_amount',
            'to_amount': 'to_amount',
            'from_payment': 'from_payment',
            'to_payment': 'to_payment',
            'from_network': 'from_network',
            'to_network': 'to_network'
        }

        self._conversion_type = conversion_type
        self._from_address = from_address
        self._to_address = to_address
        self._from_asset = from_asset
        self._to_asset = to_asset
        self._from_amount = from_amount
        self._to_amount = to_amount
        self._from_payment = from_payment
        self._to_payment = to_payment
        self._from_network = from_network
        self._to_network = to_network

    @classmethod
    def from_dict(cls, dikt: dict) -> 'ExternalConversions':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The external_conversions of this ExternalConversions.
        """
        return util.deserialize_model(dikt, cls)

    def to_dict(self, shallow=False):
        """Returns the model as a dict:

        :return: The ExternalConversions as a dict
        :rtype: dict
        """
        if not shallow:
            return Model.to_dict(self)
        return { 'conversion_type': self._conversion_type,
            'from_address': self._from_address,
            'to_address': self._to_address,
            'from_asset': self._from_asset,
            'to_asset': self._to_asset,
            'from_amount': self._from_amount,
            'to_amount': self._to_amount,
            'from_payment': self._from_payment,
            'to_payment': self._to_payment,
            'from_network': self._from_network,
            'to_network': self._to_network }


    @property
    def conversion_type(self):
        """Gets the conversion_type of this ExternalConversions.


        :return: The conversion_type of this ExternalConversions.
        :rtype: str
        """
        return self._conversion_type

    @conversion_type.setter
    def conversion_type(self, conversion_type):
        """Sets the conversion_type of this ExternalConversions.


        :param conversion_type: The conversion_type of this ExternalConversions.
        :type conversion_type: str
        """
        allowed_values = ["dex_swap", "bridge_tx"]  # noqa: E501
        if conversion_type not in allowed_values:
            raise BadUserInputException(
                "Invalid value for `conversion_type` ({0}), must be one of {1}"
                .format(conversion_type, allowed_values)
            )

        self._conversion_type = conversion_type

    @property
    def from_address(self):
        """Gets the from_address of this ExternalConversions.

        Provider of the input assets of the external conversion

        :return: The from_address of this ExternalConversions.
        :rtype: str
        """
        return self._from_address

    @from_address.setter
    def from_address(self, from_address):
        """Sets the from_address of this ExternalConversions.

        Provider of the input assets of the external conversion

        :param from_address: The from_address of this ExternalConversions.
        :type from_address: str
        """
        if from_address is None:
            raise BadUserInputException("Invalid value for `from_address`, must not be `None`")

        self._from_address = from_address

    @property
    def to_address(self):
        """Gets the to_address of this ExternalConversions.

        Receiver of the output assets of the external conversion

        :return: The to_address of this ExternalConversions.
        :rtype: str
        """
        return self._to_address

    @to_address.setter
    def to_address(self, to_address):
        """Sets the to_address of this ExternalConversions.

        Receiver of the output assets of the external conversion

        :param to_address: The to_address of this ExternalConversions.
        :type to_address: str
        """
        if to_address is None:
            raise BadUserInputException("Invalid value for `to_address`, must not be `None`")

        self._to_address = to_address

    @property
    def from_asset(self):
        """Gets the from_asset of this ExternalConversions.

        Asset converted from

        :return: The from_asset of this ExternalConversions.
        :rtype: str
        """
        return self._from_asset

    @from_asset.setter
    def from_asset(self, from_asset):
        """Sets the from_asset of this ExternalConversions.

        Asset converted from

        :param from_asset: The from_asset of this ExternalConversions.
        :type from_asset: str
        """
        if from_asset is None:
            raise BadUserInputException("Invalid value for `from_asset`, must not be `None`")

        self._from_asset = from_asset

    @property
    def to_asset(self):
        """Gets the to_asset of this ExternalConversions.

        Asset converted to

        :return: The to_asset of this ExternalConversions.
        :rtype: str
        """
        return self._to_asset

    @to_asset.setter
    def to_asset(self, to_asset):
        """Sets the to_asset of this ExternalConversions.

        Asset converted to

        :param to_asset: The to_asset of this ExternalConversions.
        :type to_asset: str
        """
        if to_asset is None:
            raise BadUserInputException("Invalid value for `to_asset`, must not be `None`")

        self._to_asset = to_asset

    @property
    def from_amount(self):
        """Gets the from_amount of this ExternalConversions.

        Amount of asset converted from

        :return: The from_amount of this ExternalConversions.
        :rtype: str
        """
        return self._from_amount

    @from_amount.setter
    def from_amount(self, from_amount):
        """Sets the from_amount of this ExternalConversions.

        Amount of asset converted from

        :param from_amount: The from_amount of this ExternalConversions.
        :type from_amount: str
        """
        if from_amount is None:
            raise BadUserInputException("Invalid value for `from_amount`, must not be `None`")

        self._from_amount = from_amount

    @property
    def to_amount(self):
        """Gets the to_amount of this ExternalConversions.

        Amount of asset converted to

        :return: The to_amount of this ExternalConversions.
        :rtype: str
        """
        return self._to_amount

    @to_amount.setter
    def to_amount(self, to_amount):
        """Sets the to_amount of this ExternalConversions.

        Amount of asset converted to

        :param to_amount: The to_amount of this ExternalConversions.
        :type to_amount: str
        """
        if to_amount is None:
            raise BadUserInputException("Invalid value for `to_amount`, must not be `None`")

        self._to_amount = to_amount

    @property
    def from_payment(self):
        """Gets the from_payment of this ExternalConversions.

        Initial payment starting the conversion process

        :return: The from_payment of this ExternalConversions.
        :rtype: str
        """
        return self._from_payment

    @from_payment.setter
    def from_payment(self, from_payment):
        """Sets the from_payment of this ExternalConversions.

        Initial payment starting the conversion process

        :param from_payment: The from_payment of this ExternalConversions.
        :type from_payment: str
        """
        if from_payment is None:
            raise BadUserInputException("Invalid value for `from_payment`, must not be `None`")

        self._from_payment = from_payment

    @property
    def to_payment(self):
        """Gets the to_payment of this ExternalConversions.

        Output payment ending the conversion process

        :return: The to_payment of this ExternalConversions.
        :rtype: str
        """
        return self._to_payment

    @to_payment.setter
    def to_payment(self, to_payment):
        """Sets the to_payment of this ExternalConversions.

        Output payment ending the conversion process

        :param to_payment: The to_payment of this ExternalConversions.
        :type to_payment: str
        """
        if to_payment is None:
            raise BadUserInputException("Invalid value for `to_payment`, must not be `None`")

        self._to_payment = to_payment

    @property
    def from_network(self):
        """Gets the from_network of this ExternalConversions.

        Network where the initial payment took place

        :return: The from_network of this ExternalConversions.
        :rtype: str
        """
        return self._from_network

    @from_network.setter
    def from_network(self, from_network):
        """Sets the from_network of this ExternalConversions.

        Network where the initial payment took place

        :param from_network: The from_network of this ExternalConversions.
        :type from_network: str
        """
        if from_network is None:
            raise BadUserInputException("Invalid value for `from_network`, must not be `None`")

        self._from_network = from_network

    @property
    def to_network(self):
        """Gets the to_network of this ExternalConversions.

        Network where the concluding payment took place

        :return: The to_network of this ExternalConversions.
        :rtype: str
        """
        return self._to_network

    @to_network.setter
    def to_network(self, to_network):
        """Sets the to_network of this ExternalConversions.

        Network where the concluding payment took place

        :param to_network: The to_network of this ExternalConversions.
        :type to_network: str
        """
        if to_network is None:
            raise BadUserInputException("Invalid value for `to_network`, must not be `None`")

        self._to_network = to_network
