# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.get_tx_io_result import GetTxIoResult
from openapi_server import util

from openapi_server.models.get_tx_io_result import GetTxIoResult  # noqa: E501

class GetTxIoResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, operation='get_tx_io', result=None):  # noqa: E501
        """GetTxIoResponse - a model defined in OpenAPI

        :param operation: The operation of this GetTxIoResponse.  # noqa: E501
        :type operation: str
        :param result: The result of this GetTxIoResponse.  # noqa: E501
        :type result: List[GetTxIoResult]
        """
        self.openapi_types = {
            'operation': str,
            'result': List[GetTxIoResult]
        }

        self.attribute_map = {
            'operation': 'operation',
            'result': 'result'
        }

        #if operation is None:
            #raise ValueError("Invalid value for `operation`, must not be `None`")  # noqa: E501
        self._operation = operation
        #if result is None:
            #raise ValueError("Invalid value for `result`, must not be `None`")  # noqa: E501
        self._result = result

    @classmethod
    def from_dict(cls, dikt) -> 'GetTxIoResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The get_tx_io_response of this GetTxIoResponse.  # noqa: E501
        :rtype: GetTxIoResponse
        """
        return util.deserialize_model(dikt, cls)

    def to_dict(self, prefix=""):
        """Returns the model as a dict:

        :return: The GetTxIoResponse as a dict
        :rtype: dict
        """
        return { 'operation': self._operation,
            'result': self._result }


    @property
    def operation(self):
        """Gets the operation of this GetTxIoResponse.


        :return: The operation of this GetTxIoResponse.
        :rtype: str
        """
        return self._operation

    @operation.setter
    def operation(self, operation):
        """Sets the operation of this GetTxIoResponse.


        :param operation: The operation of this GetTxIoResponse.
        :type operation: str
        """
        if operation is None:
            raise ValueError("Invalid value for `operation`, must not be `None`")  # noqa: E501

        self._operation = operation

    @property
    def result(self):
        """Gets the result of this GetTxIoResponse.


        :return: The result of this GetTxIoResponse.
        :rtype: List[GetTxIoResult]
        """
        return self._result

    @result.setter
    def result(self, result):
        """Sets the result of this GetTxIoResponse.


        :param result: The result of this GetTxIoResponse.
        :type result: List[GetTxIoResult]
        """
        if result is None:
            raise ValueError("Invalid value for `result`, must not be `None`")  # noqa: E501

        self._result = result
