# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.io import Io
from openapi_server import util

from openapi_server.models.io import Io  # noqa: E501

class GetTxIoParameters(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, io=None, tx_hash=None):  # noqa: E501
        """GetTxIoParameters - a model defined in OpenAPI

        :param io: The io of this GetTxIoParameters.  # noqa: E501
        :type io: Io
        :param tx_hash: The tx_hash of this GetTxIoParameters.  # noqa: E501
        :type tx_hash: str
        """
        self.openapi_types = {
            'io': Io,
            'tx_hash': str
        }

        self.attribute_map = {
            'io': 'io',
            'tx_hash': 'tx_hash'
        }

        #if io is None:
            #raise ValueError("Invalid value for `io`, must not be `None`")  # noqa: E501
        self._io = io
        #if tx_hash is None:
            #raise ValueError("Invalid value for `tx_hash`, must not be `None`")  # noqa: E501
        self._tx_hash = tx_hash

    @classmethod
    def from_dict(cls, dikt) -> 'GetTxIoParameters':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The get_tx_io_parameters of this GetTxIoParameters.  # noqa: E501
        :rtype: GetTxIoParameters
        """
        return util.deserialize_model(dikt, cls)

    def to_dict(self, prefix=""):
        """Returns the model as a dict:

        :return: The GetTxIoParameters as a dict
        :rtype: dict
        """
        return { 'io': self._io,
            'tx_hash': self._tx_hash }


    @property
    def io(self):
        """Gets the io of this GetTxIoParameters.


        :return: The io of this GetTxIoParameters.
        :rtype: Io
        """
        return self._io

    @io.setter
    def io(self, io):
        """Sets the io of this GetTxIoParameters.


        :param io: The io of this GetTxIoParameters.
        :type io: Io
        """
        if io is None:
            raise ValueError("Invalid value for `io`, must not be `None`")  # noqa: E501

        self._io = io

    @property
    def tx_hash(self):
        """Gets the tx_hash of this GetTxIoParameters.

        Transaction hash  # noqa: E501

        :return: The tx_hash of this GetTxIoParameters.
        :rtype: str
        """
        return self._tx_hash

    @tx_hash.setter
    def tx_hash(self, tx_hash):
        """Sets the tx_hash of this GetTxIoParameters.

        Transaction hash  # noqa: E501

        :param tx_hash: The tx_hash of this GetTxIoParameters.
        :type tx_hash: str
        """
        if tx_hash is None:
            raise ValueError("Invalid value for `tx_hash`, must not be `None`")  # noqa: E501

        self._tx_hash = tx_hash
