# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.values import Values
from openapi_server import util

from openapi_server.models.values import Values  # noqa: E501

class LinkUtxo(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, height=None, input_value=None, output_value=None, timestamp=None, tx_hash=None, tx_type='utxo'):  # noqa: E501
        """LinkUtxo - a model defined in OpenAPI

        :param height: The height of this LinkUtxo.  # noqa: E501
        :type height: int
        :param input_value: The input_value of this LinkUtxo.  # noqa: E501
        :type input_value: Values
        :param output_value: The output_value of this LinkUtxo.  # noqa: E501
        :type output_value: Values
        :param timestamp: The timestamp of this LinkUtxo.  # noqa: E501
        :type timestamp: int
        :param tx_hash: The tx_hash of this LinkUtxo.  # noqa: E501
        :type tx_hash: str
        :param tx_type: The tx_type of this LinkUtxo.  # noqa: E501
        :type tx_type: str
        """
        self.openapi_types = {
            'height': int,
            'input_value': Values,
            'output_value': Values,
            'timestamp': int,
            'tx_hash': str,
            'tx_type': str
        }

        self.attribute_map = {
            'height': 'height',
            'input_value': 'input_value',
            'output_value': 'output_value',
            'timestamp': 'timestamp',
            'tx_hash': 'tx_hash',
            'tx_type': 'tx_type'
        }

        if height is None:
            raise ValueError("Invalid value for `height`, must not be `None`")  # noqa: E501
        self._height = height
        if input_value is None:
            raise ValueError("Invalid value for `input_value`, must not be `None`")  # noqa: E501
        self._input_value = input_value
        if output_value is None:
            raise ValueError("Invalid value for `output_value`, must not be `None`")  # noqa: E501
        self._output_value = output_value
        if timestamp is None:
            raise ValueError("Invalid value for `timestamp`, must not be `None`")  # noqa: E501
        self._timestamp = timestamp
        if tx_hash is None:
            raise ValueError("Invalid value for `tx_hash`, must not be `None`")  # noqa: E501
        self._tx_hash = tx_hash
        if tx_type is None:
            raise ValueError("Invalid value for `tx_type`, must not be `None`")  # noqa: E501
        self._tx_type = tx_type

    @classmethod
    def from_dict(cls, dikt) -> 'LinkUtxo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The link_utxo of this LinkUtxo.  # noqa: E501
        :rtype: LinkUtxo
        """
        return util.deserialize_model(dikt, cls)

    def to_dict(self, prefix=""):
        """Returns the model as a dict:

        :return: The LinkUtxo as a dict
        :rtype: dict
        """
        return { 'height': self._height,
            'input_value': self._input_value,
            'output_value': self._output_value,
            'timestamp': self._timestamp,
            'tx_hash': self._tx_hash,
            'tx_type': self._tx_type }


    @property
    def height(self):
        """Gets the height of this LinkUtxo.

        Height  # noqa: E501

        :return: The height of this LinkUtxo.
        :rtype: int
        """
        return self._height

    @height.setter
    def height(self, height):
        """Sets the height of this LinkUtxo.

        Height  # noqa: E501

        :param height: The height of this LinkUtxo.
        :type height: int
        """
        if height is None:
            raise ValueError("Invalid value for `height`, must not be `None`")  # noqa: E501
        if height is not None and height < 1:  # noqa: E501
            raise ValueError("Invalid value for `height`, must be a value greater than or equal to `1`")  # noqa: E501

        self._height = height

    @property
    def input_value(self):
        """Gets the input_value of this LinkUtxo.


        :return: The input_value of this LinkUtxo.
        :rtype: Values
        """
        return self._input_value

    @input_value.setter
    def input_value(self, input_value):
        """Sets the input_value of this LinkUtxo.


        :param input_value: The input_value of this LinkUtxo.
        :type input_value: Values
        """
        if input_value is None:
            raise ValueError("Invalid value for `input_value`, must not be `None`")  # noqa: E501

        self._input_value = input_value

    @property
    def output_value(self):
        """Gets the output_value of this LinkUtxo.


        :return: The output_value of this LinkUtxo.
        :rtype: Values
        """
        return self._output_value

    @output_value.setter
    def output_value(self, output_value):
        """Sets the output_value of this LinkUtxo.


        :param output_value: The output_value of this LinkUtxo.
        :type output_value: Values
        """
        if output_value is None:
            raise ValueError("Invalid value for `output_value`, must not be `None`")  # noqa: E501

        self._output_value = output_value

    @property
    def timestamp(self):
        """Gets the timestamp of this LinkUtxo.

        Timestamp  # noqa: E501

        :return: The timestamp of this LinkUtxo.
        :rtype: int
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this LinkUtxo.

        Timestamp  # noqa: E501

        :param timestamp: The timestamp of this LinkUtxo.
        :type timestamp: int
        """
        if timestamp is None:
            raise ValueError("Invalid value for `timestamp`, must not be `None`")  # noqa: E501

        self._timestamp = timestamp

    @property
    def tx_hash(self):
        """Gets the tx_hash of this LinkUtxo.

        Transaction hash  # noqa: E501

        :return: The tx_hash of this LinkUtxo.
        :rtype: str
        """
        return self._tx_hash

    @tx_hash.setter
    def tx_hash(self, tx_hash):
        """Sets the tx_hash of this LinkUtxo.

        Transaction hash  # noqa: E501

        :param tx_hash: The tx_hash of this LinkUtxo.
        :type tx_hash: str
        """
        if tx_hash is None:
            raise ValueError("Invalid value for `tx_hash`, must not be `None`")  # noqa: E501

        self._tx_hash = tx_hash

    @property
    def tx_type(self):
        """Gets the tx_type of this LinkUtxo.


        :return: The tx_type of this LinkUtxo.
        :rtype: str
        """
        return self._tx_type

    @tx_type.setter
    def tx_type(self, tx_type):
        """Sets the tx_type of this LinkUtxo.


        :param tx_type: The tx_type of this LinkUtxo.
        :type tx_type: str
        """
        if tx_type is None:
            raise ValueError("Invalid value for `tx_type`, must not be `None`")  # noqa: E501

        self._tx_type = tx_type
