# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class ListEntityAddresses(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, api='entities', entity=None, operation='list_entity_addresses'):  # noqa: E501
        """ListEntityAddresses - a model defined in OpenAPI

        :param api: The api of this ListEntityAddresses.  # noqa: E501
        :type api: str
        :param entity: The entity of this ListEntityAddresses.  # noqa: E501
        :type entity: List[int]
        :param operation: The operation of this ListEntityAddresses.  # noqa: E501
        :type operation: str
        """
        self.openapi_types = {
            'api': str,
            'entity': List[int],
            'operation': str
        }

        self.attribute_map = {
            'api': 'api',
            'entity': 'entity',
            'operation': 'operation'
        }

        #if api is None:
            #raise ValueError("Invalid value for `api`, must not be `None`")  # noqa: E501
        self._api = api
        #if entity is None:
            #raise ValueError("Invalid value for `entity`, must not be `None`")  # noqa: E501
        self._entity = entity
        #if operation is None:
            #raise ValueError("Invalid value for `operation`, must not be `None`")  # noqa: E501
        self._operation = operation

    @classmethod
    def from_dict(cls, dikt) -> 'ListEntityAddresses':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The list_entity_addresses of this ListEntityAddresses.  # noqa: E501
        :rtype: ListEntityAddresses
        """
        return util.deserialize_model(dikt, cls)

    def to_dict(self, prefix=""):
        """Returns the model as a dict:

        :return: The ListEntityAddresses as a dict
        :rtype: dict
        """
        return { 'api': self._api,
            'entity': self._entity,
            'operation': self._operation }


    @property
    def api(self):
        """Gets the api of this ListEntityAddresses.


        :return: The api of this ListEntityAddresses.
        :rtype: str
        """
        return self._api

    @api.setter
    def api(self, api):
        """Sets the api of this ListEntityAddresses.


        :param api: The api of this ListEntityAddresses.
        :type api: str
        """
        if api is None:
            raise ValueError("Invalid value for `api`, must not be `None`")  # noqa: E501

        self._api = api

    @property
    def entity(self):
        """Gets the entity of this ListEntityAddresses.


        :return: The entity of this ListEntityAddresses.
        :rtype: List[int]
        """
        return self._entity

    @entity.setter
    def entity(self, entity):
        """Sets the entity of this ListEntityAddresses.


        :param entity: The entity of this ListEntityAddresses.
        :type entity: List[int]
        """
        if entity is None:
            raise ValueError("Invalid value for `entity`, must not be `None`")  # noqa: E501

        self._entity = entity

    @property
    def operation(self):
        """Gets the operation of this ListEntityAddresses.


        :return: The operation of this ListEntityAddresses.
        :rtype: str
        """
        return self._operation

    @operation.setter
    def operation(self, operation):
        """Sets the operation of this ListEntityAddresses.


        :param operation: The operation of this ListEntityAddresses.
        :type operation: str
        """
        if operation is None:
            raise ValueError("Invalid value for `operation`, must not be `None`")  # noqa: E501

        self._operation = operation
