# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class ListBlockTxs(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, api='blocks', height=None, operation='list_block_txs'):  # noqa: E501
        """ListBlockTxs - a model defined in OpenAPI

        :param api: The api of this ListBlockTxs.  # noqa: E501
        :type api: str
        :param height: The height of this ListBlockTxs.  # noqa: E501
        :type height: List[int]
        :param operation: The operation of this ListBlockTxs.  # noqa: E501
        :type operation: str
        """
        self.openapi_types = {
            'api': str,
            'height': List[int],
            'operation': str
        }

        self.attribute_map = {
            'api': 'api',
            'height': 'height',
            'operation': 'operation'
        }

        #if api is None:
            #raise ValueError("Invalid value for `api`, must not be `None`")  # noqa: E501
        self._api = api
        #if height is None:
            #raise ValueError("Invalid value for `height`, must not be `None`")  # noqa: E501
        self._height = height
        #if operation is None:
            #raise ValueError("Invalid value for `operation`, must not be `None`")  # noqa: E501
        self._operation = operation

    @classmethod
    def from_dict(cls, dikt) -> 'ListBlockTxs':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The list_block_txs of this ListBlockTxs.  # noqa: E501
        :rtype: ListBlockTxs
        """
        return util.deserialize_model(dikt, cls)

    def to_dict(self, prefix=""):
        """Returns the model as a dict:

        :return: The ListBlockTxs as a dict
        :rtype: dict
        """
        return { 'api': self._api,
            'height': self._height,
            'operation': self._operation }


    @property
    def api(self):
        """Gets the api of this ListBlockTxs.


        :return: The api of this ListBlockTxs.
        :rtype: str
        """
        return self._api

    @api.setter
    def api(self, api):
        """Sets the api of this ListBlockTxs.


        :param api: The api of this ListBlockTxs.
        :type api: str
        """
        if api is None:
            raise ValueError("Invalid value for `api`, must not be `None`")  # noqa: E501

        self._api = api

    @property
    def height(self):
        """Gets the height of this ListBlockTxs.


        :return: The height of this ListBlockTxs.
        :rtype: List[int]
        """
        return self._height

    @height.setter
    def height(self, height):
        """Sets the height of this ListBlockTxs.


        :param height: The height of this ListBlockTxs.
        :type height: List[int]
        """
        if height is None:
            raise ValueError("Invalid value for `height`, must not be `None`")  # noqa: E501

        self._height = height

    @property
    def operation(self):
        """Gets the operation of this ListBlockTxs.


        :return: The operation of this ListBlockTxs.
        :rtype: str
        """
        return self._operation

    @operation.setter
    def operation(self, operation):
        """Sets the operation of this ListBlockTxs.


        :param operation: The operation of this ListBlockTxs.
        :type operation: str
        """
        if operation is None:
            raise ValueError("Invalid value for `operation`, must not be `None`")  # noqa: E501

        self._operation = operation
