# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model_ import Model
from openapi_server.models.address import Address
from openapi_server.models.values import Values
from openapi_server import util


class NeighborAddress(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, labels: List[str]=None, value: Values=None, no_txs: int=None, address: Address=None):
        """NeighborAddress - a model defined in OpenAPI

        :param labels: The labels of this NeighborAddress.
        :param value: The value of this NeighborAddress.
        :param no_txs: The no_txs of this NeighborAddress.
        :param address: The address of this NeighborAddress.
        """
        self.openapi_types = {
            'labels': List[str],
            'value': Values,
            'no_txs': int,
            'address': Address
        }

        self.attribute_map = {
            'labels': 'labels',
            'value': 'value',
            'no_txs': 'no_txs',
            'address': 'address'
        }

        self._labels = labels
        self._value = value
        self._no_txs = no_txs
        self._address = address

    @classmethod
    def from_dict(cls, dikt: dict) -> 'NeighborAddress':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The neighbor_address of this NeighborAddress.
        """
        return util.deserialize_model(dikt, cls)

    def to_dict(self, shallow=False):
        """Returns the model as a dict:

        :return: The NeighborAddress as a dict
        :rtype: dict
        """
        if not shallow:
            return Model.to_dict(self)
        return { 'labels': self._labels,
            'value': self._value,
            'no_txs': self._no_txs,
            'address': self._address }


    @property
    def labels(self):
        """Gets the labels of this NeighborAddress.

        The neighbor's tag labels

        :return: The labels of this NeighborAddress.
        :rtype: List[str]
        """
        return self._labels

    @labels.setter
    def labels(self, labels):
        """Sets the labels of this NeighborAddress.

        The neighbor's tag labels

        :param labels: The labels of this NeighborAddress.
        :type labels: List[str]
        """

        self._labels = labels

    @property
    def value(self):
        """Gets the value of this NeighborAddress.


        :return: The value of this NeighborAddress.
        :rtype: Values
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this NeighborAddress.


        :param value: The value of this NeighborAddress.
        :type value: Values
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")

        self._value = value

    @property
    def no_txs(self):
        """Gets the no_txs of this NeighborAddress.

        number of transactions

        :return: The no_txs of this NeighborAddress.
        :rtype: int
        """
        return self._no_txs

    @no_txs.setter
    def no_txs(self, no_txs):
        """Sets the no_txs of this NeighborAddress.

        number of transactions

        :param no_txs: The no_txs of this NeighborAddress.
        :type no_txs: int
        """
        if no_txs is None:
            raise ValueError("Invalid value for `no_txs`, must not be `None`")

        self._no_txs = no_txs

    @property
    def address(self):
        """Gets the address of this NeighborAddress.


        :return: The address of this NeighborAddress.
        :rtype: Address
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this NeighborAddress.


        :param address: The address of this NeighborAddress.
        :type address: Address
        """
        if address is None:
            raise ValueError("Invalid value for `address`, must not be `None`")

        self._address = address
