# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model_ import Model
from openapi_server.models.entity import Entity
from openapi_server.models.values import Values
from openapi_server import util


class NeighborEntity(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, entity: Entity=None, labels: List[str]=None, no_txs: int=None, value: Values=None):
        """NeighborEntity - a model defined in OpenAPI

        :param entity: The entity of this NeighborEntity.
        :param labels: The labels of this NeighborEntity.
        :param no_txs: The no_txs of this NeighborEntity.
        :param value: The value of this NeighborEntity.
        """
        self.openapi_types = {
            'entity': Entity,
            'labels': List[str],
            'no_txs': int,
            'value': Values
        }

        self.attribute_map = {
            'entity': 'entity',
            'labels': 'labels',
            'no_txs': 'no_txs',
            'value': 'value'
        }

        self._entity = entity
        self._labels = labels
        self._no_txs = no_txs
        self._value = value

    @classmethod
    def from_dict(cls, dikt: dict) -> 'NeighborEntity':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The neighbor_entity of this NeighborEntity.
        """
        return util.deserialize_model(dikt, cls)

    def to_dict(self, shallow=False):
        """Returns the model as a dict:

        :return: The NeighborEntity as a dict
        :rtype: dict
        """
        if not shallow:
            return Model.to_dict(self)
        return { 'entity': self._entity,
            'labels': self._labels,
            'no_txs': self._no_txs,
            'value': self._value }


    @property
    def entity(self):
        """Gets the entity of this NeighborEntity.


        :return: The entity of this NeighborEntity.
        :rtype: Entity
        """
        return self._entity

    @entity.setter
    def entity(self, entity):
        """Sets the entity of this NeighborEntity.


        :param entity: The entity of this NeighborEntity.
        :type entity: Entity
        """
        if entity is None:
            raise ValueError("Invalid value for `entity`, must not be `None`")

        self._entity = entity

    @property
    def labels(self):
        """Gets the labels of this NeighborEntity.

        The neighbor's tag labels

        :return: The labels of this NeighborEntity.
        :rtype: List[str]
        """
        return self._labels

    @labels.setter
    def labels(self, labels):
        """Sets the labels of this NeighborEntity.

        The neighbor's tag labels

        :param labels: The labels of this NeighborEntity.
        :type labels: List[str]
        """

        self._labels = labels

    @property
    def no_txs(self):
        """Gets the no_txs of this NeighborEntity.

        number of transactions

        :return: The no_txs of this NeighborEntity.
        :rtype: int
        """
        return self._no_txs

    @no_txs.setter
    def no_txs(self, no_txs):
        """Sets the no_txs of this NeighborEntity.

        number of transactions

        :param no_txs: The no_txs of this NeighborEntity.
        :type no_txs: int
        """
        if no_txs is None:
            raise ValueError("Invalid value for `no_txs`, must not be `None`")

        self._no_txs = no_txs

    @property
    def value(self):
        """Gets the value of this NeighborEntity.


        :return: The value of this NeighborEntity.
        :rtype: Values
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this NeighborEntity.


        :param value: The value of this NeighborEntity.
        :type value: Values
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")

        self._value = value
