# coding: utf-8
from gsrest.errors import BadUserInputException
from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model_ import Model
from openapi_server.models.rate import Rate
from openapi_server import util


class Rates(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, height: int=None, rates: List[Rate]=None):
        """Rates - a model defined in OpenAPI

        :param height: The height of this Rates.
        :param rates: The rates of this Rates.
        """
        self.openapi_types = {
            'height': int,
            'rates': List[Rate]
        }

        self.attribute_map = {
            'height': 'height',
            'rates': 'rates'
        }

        self._height = height
        self._rates = rates

    @classmethod
    def from_dict(cls, dikt: dict) -> 'Rates':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The rates of this Rates.
        """
        return util.deserialize_model(dikt, cls)

    def to_dict(self, shallow=False):
        """Returns the model as a dict:

        :return: The Rates as a dict
        :rtype: dict
        """
        if not shallow:
            return Model.to_dict(self)
        return { 'height': self._height,
            'rates': self._rates }


    @property
    def height(self):
        """Gets the height of this Rates.

        Height

        :return: The height of this Rates.
        :rtype: int
        """
        return self._height

    @height.setter
    def height(self, height):
        """Sets the height of this Rates.

        Height

        :param height: The height of this Rates.
        :type height: int
        """
        if height is not None and height < 0:
            raise BadUserInputException("Invalid value for `height`, must be a value greater than or equal to `0`")

        self._height = height

    @property
    def rates(self):
        """Gets the rates of this Rates.


        :return: The rates of this Rates.
        :rtype: List[Rate]
        """
        return self._rates

    @rates.setter
    def rates(self, rates):
        """Sets the rates of this Rates.


        :param rates: The rates of this Rates.
        :type rates: List[Rate]
        """

        self._rates = rates
