# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class StatsTool(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, visible_name=None, id=None, version=None, titanium_replayable=None, responsible_for=None):  # noqa: E501
        """StatsTool - a model defined in OpenAPI

        :param visible_name: The visible_name of this StatsTool.  # noqa: E501
        :type visible_name: str
        :param id: The id of this StatsTool.  # noqa: E501
        :type id: str
        :param version: The version of this StatsTool.  # noqa: E501
        :type version: str
        :param titanium_replayable: The titanium_replayable of this StatsTool.  # noqa: E501
        :type titanium_replayable: bool
        :param responsible_for: The responsible_for of this StatsTool.  # noqa: E501
        :type responsible_for: List[str]
        """
        self.openapi_types = {
            'visible_name': str,
            'id': str,
            'version': str,
            'titanium_replayable': bool,
            'responsible_for': List[str]
        }

        self.attribute_map = {
            'visible_name': 'visible_name',
            'id': 'id',
            'version': 'version',
            'titanium_replayable': 'titanium_replayable',
            'responsible_for': 'responsible_for'
        }

        self._visible_name = visible_name
        self._id = id
        self._version = version
        self._titanium_replayable = titanium_replayable
        self._responsible_for = responsible_for

    @classmethod
    def from_dict(cls, dikt) -> 'StatsTool':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The stats_tool of this StatsTool.  # noqa: E501
        :rtype: StatsTool
        """
        return util.deserialize_model(dikt, cls)

    def to_dict(self, prefix=""):
        """Returns the model as a dict:

        :return: The StatsTool as a dict
        :rtype: dict
        """
        return { 'visible_name': self._visible_name,
            'id': self._id,
            'version': self._version,
            'titanium_replayable': self._titanium_replayable,
            'responsible_for': self._responsible_for }


    @property
    def visible_name(self):
        """Gets the visible_name of this StatsTool.


        :return: The visible_name of this StatsTool.
        :rtype: str
        """
        return self._visible_name

    @visible_name.setter
    def visible_name(self, visible_name):
        """Sets the visible_name of this StatsTool.


        :param visible_name: The visible_name of this StatsTool.
        :type visible_name: str
        """

        self._visible_name = visible_name

    @property
    def id(self):
        """Gets the id of this StatsTool.


        :return: The id of this StatsTool.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this StatsTool.


        :param id: The id of this StatsTool.
        :type id: str
        """

        self._id = id

    @property
    def version(self):
        """Gets the version of this StatsTool.


        :return: The version of this StatsTool.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this StatsTool.


        :param version: The version of this StatsTool.
        :type version: str
        """

        self._version = version

    @property
    def titanium_replayable(self):
        """Gets the titanium_replayable of this StatsTool.


        :return: The titanium_replayable of this StatsTool.
        :rtype: bool
        """
        return self._titanium_replayable

    @titanium_replayable.setter
    def titanium_replayable(self, titanium_replayable):
        """Sets the titanium_replayable of this StatsTool.


        :param titanium_replayable: The titanium_replayable of this StatsTool.
        :type titanium_replayable: bool
        """

        self._titanium_replayable = titanium_replayable

    @property
    def responsible_for(self):
        """Gets the responsible_for of this StatsTool.


        :return: The responsible_for of this StatsTool.
        :rtype: List[str]
        """
        return self._responsible_for

    @responsible_for.setter
    def responsible_for(self, responsible_for):
        """Sets the responsible_for of this StatsTool.


        :param responsible_for: The responsible_for of this StatsTool.
        :type responsible_for: List[str]
        """

        self._responsible_for = responsible_for
