# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class StatsLedgerVersion(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, nr=None, timestamp=None):  # noqa: E501
        """StatsLedgerVersion - a model defined in OpenAPI

        :param nr: The nr of this StatsLedgerVersion.  # noqa: E501
        :type nr: str
        :param timestamp: The timestamp of this StatsLedgerVersion.  # noqa: E501
        :type timestamp: str
        """
        self.openapi_types = {
            'nr': str,
            'timestamp': str
        }

        self.attribute_map = {
            'nr': 'nr',
            'timestamp': 'timestamp'
        }

        self._nr = nr
        self._timestamp = timestamp

    @classmethod
    def from_dict(cls, dikt) -> 'StatsLedgerVersion':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The stats_ledger_version of this StatsLedgerVersion.  # noqa: E501
        :rtype: StatsLedgerVersion
        """
        return util.deserialize_model(dikt, cls)

    def to_dict(self, prefix=""):
        """Returns the model as a dict:

        :return: The StatsLedgerVersion as a dict
        :rtype: dict
        """
        return { 'nr': self._nr,
            'timestamp': self._timestamp }


    @property
    def nr(self):
        """Gets the nr of this StatsLedgerVersion.


        :return: The nr of this StatsLedgerVersion.
        :rtype: str
        """
        return self._nr

    @nr.setter
    def nr(self, nr):
        """Sets the nr of this StatsLedgerVersion.


        :param nr: The nr of this StatsLedgerVersion.
        :type nr: str
        """

        self._nr = nr

    @property
    def timestamp(self):
        """Gets the timestamp of this StatsLedgerVersion.


        :return: The timestamp of this StatsLedgerVersion.
        :rtype: str
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this StatsLedgerVersion.


        :param timestamp: The timestamp of this StatsLedgerVersion.
        :type timestamp: str
        """

        self._timestamp = timestamp
