# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model_ import Model
from openapi_server.models.address_tag import AddressTag
from openapi_server.models.address_tags import AddressTags
from openapi_server.models.entity_tag import EntityTag
from openapi_server.models.entity_tags import EntityTags
from openapi_server import util


class Tags(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, entity_tags: List[EntityTag]=None, next_page: str=None, address_tags: List[AddressTag]=None):
        """Tags - a model defined in OpenAPI

        :param entity_tags: The entity_tags of this Tags.
        :param next_page: The next_page of this Tags.
        :param address_tags: The address_tags of this Tags.
        """
        self.openapi_types = {
            'entity_tags': List[EntityTag],
            'next_page': str,
            'address_tags': List[AddressTag]
        }

        self.attribute_map = {
            'entity_tags': 'entity_tags',
            'next_page': 'next_page',
            'address_tags': 'address_tags'
        }

        self._entity_tags = entity_tags
        self._next_page = next_page
        self._address_tags = address_tags

    @classmethod
    def from_dict(cls, dikt: dict) -> 'Tags':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The tags of this Tags.
        """
        return util.deserialize_model(dikt, cls)

    def to_dict(self, shallow=False):
        """Returns the model as a dict:

        :return: The Tags as a dict
        :rtype: dict
        """
        if not shallow:
            return Model.to_dict(self)
        return { 'entity_tags': self._entity_tags,
            'next_page': self._next_page,
            'address_tags': self._address_tags }


    @property
    def entity_tags(self):
        """Gets the entity_tags of this Tags.


        :return: The entity_tags of this Tags.
        :rtype: List[EntityTag]
        """
        return self._entity_tags

    @entity_tags.setter
    def entity_tags(self, entity_tags):
        """Sets the entity_tags of this Tags.


        :param entity_tags: The entity_tags of this Tags.
        :type entity_tags: List[EntityTag]
        """
        if entity_tags is None:
            raise ValueError("Invalid value for `entity_tags`, must not be `None`")

        self._entity_tags = entity_tags

    @property
    def next_page(self):
        """Gets the next_page of this Tags.


        :return: The next_page of this Tags.
        :rtype: str
        """
        return self._next_page

    @next_page.setter
    def next_page(self, next_page):
        """Sets the next_page of this Tags.


        :param next_page: The next_page of this Tags.
        :type next_page: str
        """

        self._next_page = next_page

    @property
    def address_tags(self):
        """Gets the address_tags of this Tags.


        :return: The address_tags of this Tags.
        :rtype: List[AddressTag]
        """
        return self._address_tags

    @address_tags.setter
    def address_tags(self, address_tags):
        """Sets the address_tags of this Tags.


        :param address_tags: The address_tags of this Tags.
        :type address_tags: List[AddressTag]
        """
        if address_tags is None:
            raise ValueError("Invalid value for `address_tags`, must not be `None`")

        self._address_tags = address_tags
