# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.tx_account import TxAccount
from openapi_server import util

from openapi_server.models.tx_account import TxAccount  # noqa: E501

class TxsAccount(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, next_page=None, txs=None):  # noqa: E501
        """TxsAccount - a model defined in OpenAPI

        :param next_page: The next_page of this TxsAccount.  # noqa: E501
        :type next_page: str
        :param txs: The txs of this TxsAccount.  # noqa: E501
        :type txs: List[TxAccount]
        """
        self.openapi_types = {
            'next_page': str,
            'txs': List[TxAccount]
        }

        self.attribute_map = {
            'next_page': 'next_page',
            'txs': 'txs'
        }

        self._next_page = next_page
        self._txs = txs

    @classmethod
    def from_dict(cls, dikt) -> 'TxsAccount':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The txs_account of this TxsAccount.  # noqa: E501
        :rtype: TxsAccount
        """
        return util.deserialize_model(dikt, cls)

    def to_dict(self, prefix=""):
        """Returns the model as a dict:

        :return: The TxsAccount as a dict
        :rtype: dict
        """
        return { 'next_page': self._next_page,
            'txs': self._txs }


    @property
    def next_page(self):
        """Gets the next_page of this TxsAccount.


        :return: The next_page of this TxsAccount.
        :rtype: str
        """
        return self._next_page

    @next_page.setter
    def next_page(self, next_page):
        """Sets the next_page of this TxsAccount.


        :param next_page: The next_page of this TxsAccount.
        :type next_page: str
        """

        self._next_page = next_page

    @property
    def txs(self):
        """Gets the txs of this TxsAccount.


        :return: The txs of this TxsAccount.
        :rtype: List[TxAccount]
        """
        return self._txs

    @txs.setter
    def txs(self, txs):
        """Sets the txs of this TxsAccount.


        :param txs: The txs of this TxsAccount.
        :type txs: List[TxAccount]
        """

        self._txs = txs
