# coding: utf-8
from graphsenselib.errors import BadUserInputException
from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model_ import Model
from openapi_server import util


class UserTagReportResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id: str=None):
        """UserTagReportResponse - a model defined in OpenAPI

        :param id: The id of this UserTagReportResponse.
        """
        self.openapi_types = {
            'id': str
        }

        self.attribute_map = {
            'id': 'id'
        }

        self._id = id

    @classmethod
    def from_dict(cls, dikt: dict) -> 'UserTagReportResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The user_tag_report_response of this UserTagReportResponse.
        """
        return util.deserialize_model(dikt, cls)

    def to_dict(self, shallow=False):
        """Returns the model as a dict:

        :return: The UserTagReportResponse as a dict
        :rtype: dict
        """
        if not shallow:
            return Model.to_dict(self)
        return { 'id': self._id }


    @property
    def id(self):
        """Gets the id of this UserTagReportResponse.

        Id of the reported tag

        :return: The id of this UserTagReportResponse.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this UserTagReportResponse.

        Id of the reported tag

        :param id: The id of this UserTagReportResponse.
        :type id: str
        """

        self._id = id
