name: docker build

on:
  push:

permissions:
  contents: read


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Image smoke test
        run: |
          docker build .
